### ISSUE TITLE
0.6.2 pypi release is missing source distribution

### ISSUE THREAD

**Issue by noname77** [mongodb-labs/mongo-arrow#111]
Hi,

Im on an aarch64 platform and trying to update to the latest version im getting:
```
$ uname -a
Linux 7dc3eb8d2f89 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

$ python -m pip install pymongoarrow==0.6.2
ERROR: Could not find a version that satisfies the requirement pymongoarrow==0.6.2 (from versions: 0.1.1, 0.2.0, 0.3.0, 0.4.0.dev0, 0.4.0, 0.5.0, 0.5.1)
ERROR: No matching distribution found for pymongoarrow==0.6.2
```

Looking at [PyPI downloads](https://pypi.org/project/pymongoarrow/0.6.2/#files), it seems the latest release is missing the source distribution
![image](https://user-images.githubusercontent.com/5903414/203782633-4204474d-fbbd-40bc-9651-2eda72b5467b.png)

compared to the [0.5.1 release](https://pypi.org/project/pymongoarrow/0.5.1/#files)
![image](https://user-images.githubusercontent.com/5903414/203783274-7bef6a92-3f3a-4ef4-a749-da01f6831926.png)

Could you add a source distribution, please?

Best,
Wiktor

**Comment by blink1073** [comment]
Thank you for the heads up!  I have uploaded the file.

**Comment by blink1073** [comment]
Moved the issue to https://jira.mongodb.org/browse/ARROW-130
