### ISSUE TITLE
pymongoarrow does not return nested fields

### ISSUE THREAD

**Issue by samshipengs** [mongodb-labs/mongo-arrow#124]
I'm trying out `pymongoarrow` to fetch a large dataset, with regular pymongo, I'm able to get all the fields that I needed, but with pymongoarrow it seems to not return any field with nested values (e.g. dict), did I miss something?

**Comment by ShaneHarvey** [comment]
Thanks @samshipengs, support for nested fields was merged recently (in https://github.com/mongodb-labs/mongo-arrow/commit/b9c5164037a4e6280e17597f8e5ca6ddf137c6d1) and will be released soon.

**Comment by samshipengs** [comment]
Good to hear that, thanks!
