### ISSUE TITLE
ARROW-175 Bug: nested data seems to be decoded even if not in schema

### ISSUE THREAD

**Issue by sibbiii** [mongodb-labs/mongo-arrow#164]
Hi,

I found another issue with version 1.0.1 that is a little bit tricky, 
so I spend some time to create a minimal example:

Assume you have a collection with some fields that fit a certain schema.
Now you add a new key that is not in the schema so this new key should be ignored when aggregate_arrow_all is called:

```
    collection.insert_one(
        {'_id': 0,
         'new_key': 1000000000
         })

    collection.insert_one(
        {'_id': 1,
         'new_key': 1.0e50
         })

    schema = pymongoarrow.api.Schema(
        {'_id': pa.int32()
         })

    df = pymongoarrow.api.aggregate_arrow_all(collection, [{'$sort': {'_id': 1}}], schema=schema)
```

all works as expected. So far so good. This means that aggregate_arrow_all does not break even if new fields with contradicting data types are added to the collection. 

Now the same example with a nested new key:

```
    temp_collection._collection.insert_one(
        {'_id': 0,
         'obj': {'a': 1,
                 'new_key': 1000000000}
         })

    temp_collection._collection.insert_one(
        {'_id': 1,
         'obj': {'a': 1,
                 'new_key': 1.0e50}
         })

    schema = pymongoarrow.api.Schema(
        {'_id': pa.int32(),
         'obj': {'a': pa.int32()}
         })

    df = pymongoarrow.api.aggregate_arrow_all(collection, [{'$sort': {'_id': 1}}], schema=schema)
```

This raises the error 
```
pymongoarrow\lib.pyx:284: in pymongoarrow.lib.process_raw_bson_stream
OverflowError: Python int too large to convert to C long
pymongoarrow\lib.pyx:507: OverflowError
```

**But there is no reason for this error as the `new_key` should *not* even be decoded as it is not in the schema.** 

Ps.: I could remove `new_key` by a projection if I knew that it exists (which I do not know) or define all fields that I have within the schema with a projection (that leads to crazy long projections if importing 30+ fields). Interestingly, on root level it works flawlessly, the issue just arises with nested keys so maybe this is really a bug.

Ps.: If I can help by making more tests please come back to me, I am happy to contribute if i can.

Thanks,
Sebastian

**Comment by ShaneHarvey** [comment]
Thanks @sibbiii! This appears to be a bug in `Schema._get_projection`. 
```python
>>> import pymongoarrow.api
>>> import pyarrow as pa
>>> schema = pymongoarrow.api.Schema({'_id': pa.int32(), 'obj': {'a': pa.int32()}})
>>> schema._get_projection()
{'_id': True, 'obj': True}
```

The expected behavior should be:
```python
>>> schema._get_projection()
{'_id': True, 'obj': {'a': True}}
```

**Comment by sibbiii** [comment]
works as promised, thank you very much
