### ISSUE TITLE
java version

### ISSUE THREAD

**Issue by febinct** [mongodb-labs/mongo-arrow#183]
any plan to add a java version of this library

**Comment by ashni-mongodb** [comment]
Hey! Appreciate you asking. Nothing in the immediate future, but we're happy to explore if there's sufficient user interest.

If you think it'd be valuable to have a Java version of this library, could you file a feature request [here](https://feedback.mongodb.com/forums/924286-drivers?category_id=370744) and include any details about your specific use case? Others will be able to vote on the request and we'll be able to track interest and reach out as needed. Thank you!
