### ISSUE TITLE
Bump Pyarrow supported to latest - 16.1 (May 14 2024)

### ISSUE THREAD

**Issue by rxm7706** [mongodb-labs/mongo-arrow#217]
Current pin in version 1.4.0 is  "pyarrow>=16.0,<16.1.0"
    https://github.com/mongodb-labs/mongo-arrow/blob/1.4.0/bindings/python/pyproject.toml
Would it be possible to to support the latest version too - 16.1.0 
   https://pypi.org/project/pyarrow/
It prevents downgrading pyarrow to install
   [mongo-arrow. ](https://pypi.org/project/pymongoarrow/)
Thank you and Regards.

**Comment by blink1073** [comment]
Hi @rxm7706, we're tracking this in https://jira.mongodb.org/browse/ARROW-235.  I made an attempt in to support it for 1.4.0 but ran into test failures.
