### ISSUE TITLE
np.float32 not supported?

### ISSUE THREAD

**Issue by makarr** [mongodb-labs/mongo-arrow#224]
Hi there. This works:

```
data = {'arr': np.random.rand(4)}
write(col, data)
```

This doesn't work:

```
data = {'arr': np.random.rand(4).astype(np.float32)}
write(col, data)
```

This doesn't work either:

```
data = [{'arr': np.random.rand(4).astype(np.float32)}]
df = pd.DataFrame.from_records(data)
write(col, df)
```

However, this _does_ work.:

```
data = [{'arr': np.random.rand(4).astype(np.float32)}]
df = pd.DataFrame.from_records(data)
table = pa.Table.from_pandas(df)
assert table['arr'].nbytes == 20
write(col, df)
```

Yet this assert fails since the table is loaded as float64:

```
table = col.find_arrow_all([])
assert table['arr'].nbytes == 20
```

No luck specifying the data type in the schema either. pyarrow raises a DataType error:

```
from pymongoarrow.api import Schema
from pyarrow import list_, float32
from bson.objectid import ObjectId
schema = Schema({'_id': ObjectId, 'arr': list_(float32())})
table = col.find_arrow_all([], schema=schema)
```

Desired behavior:

```
data = {'arr': np.random.rand(4).astype(np.float32)}
write(col, data)
arr = col.find_numpy_all([])['arr']
assert arr.dtype == np.float32
```

It would also be nice to have the assurance that only 32-bit floats are being saved to disk.

Versions:
```
python=3.12.4
pyarrow=16.1.0
pymongoarrow=1.4.0
pymongo=4.8.0
pandas=2.2.2
numpy=1.26.4
```

**Comment by ShaneHarvey** [comment]
MongoDB does not have a 32-bit float type. It only has 32-bit int, 64-bit int, 64-bit float, and 128-bit decimal: https://bsonspec.org/spec.html

If you attempt to write a 32-bit float type to MongoDB it will be stored as a 64-bit float.

**Comment by makarr** [comment]
Thanks Shane, that clears things up.

**Comment by ShaneHarvey** [comment]
For reference here's the current behavior:
```python
>>> data = {'arr': np.random.rand(4).astype(np.float32)}
>>> write(col, data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shane/git/mongo-arrow/bindings/python/pymongoarrow/api.py", line 464, in write
    _validate_schema([i.dtype for i in tabular.values()])
  File "/Users/shane/git/mongo-arrow/bindings/python/pymongoarrow/types.py", line 330, in _validate_schema
    raise ValueError(msg)
ValueError: Unsupported data type "float32" in schema
```
We could consider automatically casting 32-bit floats to 64-bit floats but we haven't implemented that yet. For now, the app should cast before calling write() if they desire that behavior.

**Comment by peter-mitrano-bg** [comment]
Just one person's opinion, but I'd be happy with automatically up-casting to float64 to make things more frictionless.
