### ISSUE TITLE
chore: Update Packaging Pin - to support latest 24.1

### ISSUE THREAD

**Issue by rxm7706** [mongodb-labs/mongo-arrow#229]
https://github.com/mongodb-labs/mongo-arrow/blob/fffe5bb8634fda82309429e96fdc65a0c33ce9cd/bindings/python/pyproject.toml#L40
    "packaging >=23.2,<24",

Packaging - latest version is 24.1, since its used in many core build systems as a dependency- installing mongoarrow currently downgrades the environment. 

Would it be possible to see if packaging >=23.2 can be supported (without upper bound) to give users a more compatible experience. 

Thank you and Regards.

**Comment by blink1073** [comment]
Hi @rxm7706, I opened https://jira.mongodb.org/browse/ARROW-246 to track this issue, and will make a 1.15.1 release next week.
