### ISSUE TITLE
Question: Is mongo-arrow thread-safe for concurrent queries using asyncio.to_thread?

### ISSUE THREAD

**Issue by houyingkun** [mongodb-labs/mongo-arrow#232]
Hello mongo-arrow maintainers,

I'm currently exploring the use of mongo-arrow in a project that requires concurrent querying capabilities. I would like to understand more about the thread safety aspects of mongo-arrow. Specifically, can I safely use asyncio.to_thread to perform concurrent queries with mongo-arrow?

Thank you for your assistance!

**Comment by ShaneHarvey** [comment]
Yes this library is thread safe.
