### ISSUE TITLE
pymongoarrow win64 install incomplete?

### ISSUE THREAD

**Issue by Valence-Shinei** [mongodb-labs/mongo-arrow#252]
Good evening,
I'm attempting to use pymongoarrow with pymongo, but I'm running into some issues. I am unable to share much technical detail due to the proprietary nature of my work =/ but I did include a screenshot to highlight my concern.

For context, I have a working setup where I can use my uri to connect pymongo 4.10.1 to the cluster and navigating down to the desired database and collection, run a client.database.collection.find_one() query/method. That's great ^=^ ! However, in trying to use pymongoarrow for a better dataframe experience, I can't seem to use the library.

The pip install seems to work well, and reading through the  Open Issues, I even tried downgrading both pymongo and pymongoarrow, but to no avail as I'm still facing the same issue:

For some reason, pymongoarrow doesn't appear to have .monkey or .api modules or classes, only listing the modules and instance in the shared screenshot. As such, I'm not able to use pymongoarrow as intended. Please advise and thank you for your dedication building this project and your time to review this request!

Respectfully,
Valence-Shinej

![20241114_191856](https://github.com/user-attachments/assets/72a2abca-0cce-48f3-9ca8-e73abd6b98a3)

**Comment by blink1073** [comment]
Hi @Valence-Shinei, the top level `__init__.py` does not export those symbols, you have to import from the submodule, e.g. `from pymongoarrow.api import aggregate_arrow_all`.

**Comment by Valence-Shinei** [comment]
There we go, that worked, thank you 🤝 and sorry for the inconvenience 👋!

**Comment by blink1073** [comment]
No problem!
