### ISSUE TITLE
Compatibility with PyMongo 4.0?

### ISSUE THREAD

**Issue by Claire-Eleutheriane** [mongodb-labs/mongo-arrow#55]
I have seen on documentation that PyMongoArrow is not compatible with Pymongo >= 4.0.
Is it still true  for PyMongoArrow 0.2.0?
 
Thanks in advance !

**Comment by blink1073** [comment]
Good catch!  Do you mind submitting a PR to update the installation guide?

**Comment by blink1073** [comment]
Oh, and to answer your question, we support PyMongo 4.0 as of 0.2.0.

**Comment by Claire-Eleutheriane** [comment]
Thanks!
