### ISSUE TITLE
TypeError: <lambda>() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by asicoderOfficial** [mongodb-labs/mongo-arrow#77]
When I try to create a Schema from the following dict: `{'_id': <class 'bson.objectid.ObjectId'>, 'date': <class 'datetime.datetime'>, 'ticker': <class 'str'>, 'pca_0': <class 'float'>, 'y': <class 'float'>}`
I get the error: TypeError: _<lambda>() takes 0 positional arguments but 1 was given_
In types (https://github.com/mongodb-labs/mongo-arrow/blob/main/bindings/python/pymongoarrow/types.py), I see that there is a dict that converts Python types to Bson types. I did my own dict, which is the same, but removing the 'lambda:' from each key-value pair, and it solved the problem. I am just reporting this to see if it can help someone or it is an error.

**Comment by blink1073** [comment]
Thanks @asicoderOfficial, this was fixed in #72.  We're nearing a 0.4.0 release which will have the fix.

**Comment by asicoderOfficial** [comment]
You are welcome! :D
